image: node:carbon

variables:
  NODE_ENV: test
  CI: 'true'

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

before_script:
  - npm install

# Tests Job
main_test:
  script:
    - npm test -- --coverage
  # Source: 
  # https://github.com/Lingvokot/gitlab-ci-scripts/blob/master/README.md#unrelated-notes-on-gitlab-ci-setup
  coverage: '/All files(?:\s*\|\s*\d*\.?\d+\s*){3}\|\s*((\d*\.?\d+))\s*\|/'

# Runs linter and prints warnings
linter:
  script: npm run lint
  allow_failure: true
