version: 2
jobs:
  build:
    working_directory: ~/platform-wallet
    docker:
    - image: node:8-alpine
    steps:
      - run:
          name: apk update
          command: apk update
      - run:
          name: apk install git and ssh
          command: apk i git ssh
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm install
          command: npm i
      - save_cache: 
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: run tests
          command: CI=true npm test --all --ci
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
