version: 2
jobs:
  build:
    working_directory: ~/platform-wallet
    docker:
    - image: circleci/node:8-stretch-browsers
    # - image: node:8-alpine
    steps:
      # - run:
      #     name: Alpine update and install deps
      #     command: apk --update add git python make g++
      - checkout
      # - restore_cache:
      #     key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: NPM install packages
          command: npm i
      - save_cache: 
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: CI=true npm test --all --ci
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
